"""Typed planning scaffolding for DISSOLVE orchestration."""

from .capability_registry import (
    ARTIFACT_TYPES,
    assert_valid_capability_registry,
    get_default_capability_registry,
    validate_capability_registry,
    validate_plan_against_registry,
)
from .compiler import (
    COMPILER_VERSION,
    CompileResult,
    PlannerBackend,
    compile_request,
    compile_shadow_diagnostics,
)
from .config import PlannerConfig, get_planner_config, get_typed_planner_mode
from .executor import (
    StepCallableResult,
    VerificationResult,
    authorize_step,
    create_execution_ledger,
    next_runnable_step,
    record_step_result,
    run_plan,
    validate_execution_plan,
    verify_step_outputs,
)
from .extractors import ExtractedFacts, extract_facts
from .guard import (
    FinalSynthesisValidation,
    PlanGuardDecision,
    evaluate_plan_tool_call,
    validate_final_synthesis_sources,
)
from .models import (
    ArtifactContract,
    CapabilitySpec,
    CountConstraint,
    DataRequirement,
    ExecutionLedger,
    FinalResponseContract,
    InputContract,
    MissingInput,
    OutputContract,
    PlanAssumption,
    PlanStep,
    RequestPlan,
    RetryPolicy,
    StepBudget,
    StepExecutionRecord,
    TextRequirement,
    is_non_trivial_request,
)
from .runtime import TypedRuntimeResult, run_typed_runtime
from .runtime_paths import normalize_runtime_path, resolve_runtime_output_dir
from .runtime_persistence import RuntimeArtifactManifest, persist_runtime_artifacts
from .runtime_production_wrappers import get_production_runtime_callable_registry
from .runtime_wrappers import (
    artifact_frames_from_contracts,
    get_runtime_callable_registry,
    make_static_artifact_wrapper,
    wrap_legacy_callable,
)
from .typed_runtime_context import (
    HydratedRuntimeContext,
    TypedRuntimeContextSnapshot,
    collect_recent_typed_runtime_snapshots,
    maybe_hydrate_context_for_selected_followup,
)
from .typed_runtime_followups import (
    TypedRuntimeArtifactReference,
    TypedRuntimeFollowupDecision,
    format_typed_artifact_summary,
    maybe_answer_typed_runtime_followup,
)
from .typed_runtime_integration import (
    RuntimeProgressSummary,
    TypedRuntimeMiddleware,
    format_typed_runtime_failure,
    format_typed_runtime_success,
    maybe_run_typed_runtime,
    summarize_typed_runtime_progress,
)
from .validators import validate_compiled_plan, validate_required_tool_inputs

__all__ = [
    "ARTIFACT_TYPES",
    "ArtifactContract",
    "CapabilitySpec",
    "COMPILER_VERSION",
    "CompileResult",
    "CountConstraint",
    "DataRequirement",
    "ExecutionLedger",
    "ExtractedFacts",
    "FinalResponseContract",
    "HydratedRuntimeContext",
    "InputContract",
    "MissingInput",
    "OutputContract",
    "PlanAssumption",
    "PlanStep",
    "PlanGuardDecision",
    "PlannerConfig",
    "PlannerBackend",
    "RequestPlan",
    "RetryPolicy",
    "RuntimeArtifactManifest",
    "RuntimeProgressSummary",
    "StepBudget",
    "StepCallableResult",
    "StepExecutionRecord",
    "TextRequirement",
    "TypedRuntimeArtifactReference",
    "TypedRuntimeContextSnapshot",
    "TypedRuntimeFollowupDecision",
    "TypedRuntimeResult",
    "TypedRuntimeMiddleware",
    "VerificationResult",
    "artifact_frames_from_contracts",
    "assert_valid_capability_registry",
    "authorize_step",
    "compile_request",
    "compile_shadow_diagnostics",
    "collect_recent_typed_runtime_snapshots",
    "create_execution_ledger",
    "evaluate_plan_tool_call",
    "extract_facts",
    "get_default_capability_registry",
    "get_planner_config",
    "get_production_runtime_callable_registry",
    "get_runtime_callable_registry",
    "get_typed_planner_mode",
    "format_typed_runtime_failure",
    "format_typed_runtime_success",
    "format_typed_artifact_summary",
    "is_non_trivial_request",
    "make_static_artifact_wrapper",
    "maybe_answer_typed_runtime_followup",
    "maybe_hydrate_context_for_selected_followup",
    "maybe_run_typed_runtime",
    "next_runnable_step",
    "normalize_runtime_path",
    "persist_runtime_artifacts",
    "record_step_result",
    "resolve_runtime_output_dir",
    "run_plan",
    "run_typed_runtime",
    "summarize_typed_runtime_progress",
    "validate_final_synthesis_sources",
    "validate_capability_registry",
    "validate_compiled_plan",
    "validate_execution_plan",
    "validate_plan_against_registry",
    "validate_required_tool_inputs",
    "verify_step_outputs",
    "wrap_legacy_callable",
]
